beer_stuff/beer/urls.py
from django.conf.urls import url
from beer import views

app_name = 'beer'

urlpatterns = [
    url(r'^$', views.BeerListView.as_view(), name='list'),
    url(r'^types/$', views.BeerTypeListView.as_view(), name='beer_type_list'),
    url(r'^types/(?P<pk>[-\w]+)/$', views.BeerTypeDetailView.as_view(), name='beertypedetail'),
    url(r'^(?P<pk>[-\w]+)/$', views.BeerDetailView.as_view(), name='detail'),
]

beer_stuff/beer_locations/urls.py
from django.conf.urls import url
from beer_locations import views

app_name = 'beer_locations'

urlpatterns = [
    url(r'^$', views.BeerLocationsListView.as_view(), name='list')
]

beer_stuff/beer_stuff/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from beercount import views as beercount_views
from beer import views as beer_views
from locations import views as location_views
from beer_locations import views as beer_locations_views

urlpatterns = [
    url(r'^$', beercount_views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^beercount/', include('beercount.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^beer-locations/', include('beer_locations.urls')),
    url(r'^ratings/', include('ratings.urls')),
    url(r'^logout/$', beercount_views.user_logout, name='logout'),
    url(r'^beer/',include('beer.urls'), name='beer'),
]

beer_stuff/beercount/urls.py
from django.conf.urls import url
from beercount import views

app_name = 'beercount'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login')
]

beer_stuff/locations/urls.py
from django.conf.urls import url
from . import views

app_name = 'locations'

urlpatterns = [
    url(r'^types/$', views.LocationTypeListView.as_view(), name='location_type_list'),
    url(r'^types/(?P<pk>[-\w]+)/$',
        views.LocationTypeDetailView.as_view(),
        name='location_type_detail'),
    url(r'^$', views.LocationListView.as_view(), name='location_list'),
    url(r'^(?P<pk>[-\w]+)/$', views.LocationDetailView.as_view(), name='location_detail'),
]

beer_stuff/ratings/urls.py
from django.conf.urls import url
from . import views

app_name = 'ratings'

urlpatterns = [
    url(r'^$', views.RatingListView.as_view(), name="rating_list"),
    url(r'^add/$', views.RatingCreate.as_view(), name='rating_create'),
    url(r'^(?P<pk>[-\w]+)/$', views.RatingDetailView.as_view(), name='rating_detail'),
]

beer_stuff/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'beercount/style.css' %}">
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113860490-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-113860490-1');
</script>
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top' id="topmenu">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">BeerD</a>
        </div>
        <div class="collapse navbar-collapse" id="nav-collapse">

        <ul class="nav navbar-nav">
          <li>
            <a class="navbar-link" href="{% url 'beer:list' %}">Beers</a>

          </li>

          <li><a class="navbar-link" href="{% url 'locations:location_list' %}">Locations</a></li>
          <li><a class="navbar-link" href="{% url 'beer_locations:list' %}">Beer Prices</a></li>
          <li><a class="navbar-link" href="{% url 'ratings:rating_list' %}">Ratings</a></li>
          <li><a class="navbar-link" href="{% url 'ratings:rating_create' %}">Add rating</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'beercount:user_login' %}">Sign In</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li class="pull-right"><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

beer_stuff/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to BeerD</h1>
    <h2>A place where you can find best quality beer at the best price, near you</h2>
  </div>
{% endblock %}