beer_stuff/beer/urls.py
from django.conf.urls import url
from beer import views

app_name = 'beer'

urlpatterns = [
    url(r'^$', views.BeerListView.as_view(), name='list'),
    url(r'^types/$', views.BeerTypeListView.as_view(), name='beer_type_list'),
    url(r'^types/(?P<pk>[-\w]+)/$', views.BeerTypeDetailView.as_view(), name='beertypedetail'),
    url(r'^(?P<pk>[-\w]+)/$', views.BeerDetailView.as_view(), name='detail'),
]

beer_stuff/beer_stuff/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from beercount import views as beercount_views
from beer import views as beer_views
from locations import views as location_views
from beer_locations import views as beer_locations_views

urlpatterns = [
    url(r'^$', beercount_views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^beercount/', include('beercount.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^beer-locations/', include('beer_locations.urls')),
    url(r'^ratings/', include('ratings.urls')),
    url(r'^logout/$', beercount_views.user_logout, name='logout'),
    url(r'^beer/',include('beer.urls'), name='beer'),
]

beer_stuff/beer/models.py
from django.db import models

# Create your models here.
class BeerType(models.Model):
    """
    Class that defines type of the beer
    """
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=5000)

    def __str__(self):
        return self.name

class Beer(models.Model):
    """
    Class that defines beer
    """
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=5000)
    beer_type = models.ForeignKey(BeerType, related_name='beers', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

beer_stuff/beer/views.py
from django.views.generic import ListView, DetailView
from . import models
# Create your views here.

class BeerTypeListView(ListView):
    model = models.BeerType

class BeerTypeDetailView(DetailView):
    model = models.BeerType
    template_name = 'beer/beer_type_detail.html'

class BeerListView(ListView):
    model = models.Beer

class BeerDetailView(DetailView):
    model = models.Beer
    template_name = 'beer/beer_detail.html'

beer_stuff/beer/templates/beer/beer_base.html
{% extends "base.html" %}

beer_stuff/beer/templates/beer/beer_detail.html
{% extends "beer/beer_base.html" %}
{% block body_block %}
<h1>Beer Details:</h1>
<p><b>Name:</b> {{beer.name}}</p>
<p><b>Beer description:</b> {{beer.description}}</p>
<p><b>Beer type:</b> <a href="{% url 'beer:beertypedetail' pk=beer.beer_type.id %}">{{beer.beer_type.name}}</a></p>
<p><b>Beer type description:</b> {{beer.beer_type.description}}</p>
{% endblock %}

beer_stuff/beer/templates/beer/beer_list.html
{% extends "beer/beer_base.html" %}
{% block body_block %}
  <h1>List of the beers you can get nearby:</h1>
  {% for beer in beer_list %}
    <h2><a href="{{beer.id}}">{{beer.name}}</a></h2>
  {% endfor %}
{% endblock %}

beer_stuff/beer/templates/beer/beer_type_detail.html
{% extends "beer/beer_base.html" %}
{% block body_block %}
<h1>Beer Type Details:</h1>
<p><b>Name:</b> {{beertype.name}}</p>
<p><b>Description:</b> {{beertype.description}}</p>
  <h3>Beers of this type</h3>
<ul>
  {% for beer in beertype.beers.all %}
      <li><a href="{% url 'beer:detail' pk=beer.id %}">{{beer.name}}</a></li>
  {% endfor %}
</ul>
{% endblock %}

beer_stuff/beer/templates/beer/beertype_list.html
{% extends "beer/beer_base.html" %}
{% block body_block %}
  <h1>List of all the beer types!</h1>
  <ol>
    {% for beer_type in beertype_list %}
      <h2><li><a href="{{beer_type.id}}">{{beer_type.name}}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock %}